language: php

php:
  - 5.3
  - 5.4

before_script:
  - cp app/config/parameters.ini.travis app/config/parameters.ini
  - mkdir -p app/cache app/logs
  - php bin/vendors install
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load

script: "phpunit -c app/"

notifications:
  email:
    on_faiulre: always
    on_success: change
