imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    esi:
        enabled:     true
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_base_urls:
            http:
                - http://content1.christian.soronellas.es
                - http://content2.christian.soronellas.es
                - http://content3.christian.soronellas.es
        assets_version_format: v%%2$s/%%1$s
        assets_version: 1
    default_locale: %locale%
    session: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
        - "ChristianSoronellasBlogBundle"
        - "ChristianSoronellasBackofficeBundle"
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool: { type: memory }
    
# Gravatar config
ornicar_gravatar: ~

# Gregwar FormBundle
gregwar_form: ~

# StofDoctrineExtensionsBundle
stof_doctrine_extensions:
    default_locale: es_ES
    orm:
        default:
          sluggable: true
          timestampable: true

ornicar_akismet:
    api_key:        %akismet_apikey%
    url:            %akismet_blogurl%