ChristianSoronellasBlogBundle:
    resource: "@ChristianSoronellasBlogBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    pattern:   /admin/login
    defaults:  { _controller: AcmeSecurityBundle:Security:login }

login_check:
    pattern:   /admin/login-check

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal