<?php

namespace ChristianSoronellas\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findAllOrderedByCreatedAt()
    {
        $q = $this->getEntityManager()->createQuery(
            'SELECT c, p
             FROM ChristianSoronellasBlogBundle:Comment c
               JOIN c.post p
             ORDER BY c.created_at DESC'
        );

        return $q->getResult();
    }
}