<?php

namespace ChristianSoronellas\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ChristianSoronellas\BlogBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    
}